### PR TITLE
Feature/make auth work with v5.5 firmware

### PR DESCRIPTION
**Pull request by frallain**
This PR makes it possible to use `hikvision-client` with Hikvision cameras with firmware>=v5.5.0 since this firmware uses Digest Auth by default, which was not handled previously in this library.
2 unit tests and test coverage have been added, and a working CircleCI config as well, CircleCI needs to be configured to run on this repo though (free of charge).

### CODE REVIEW

**Comment by MissiaL** [comment]
Very cool! Thanks so much @frallain

**Comment by frallain** [comment]
@MissiaL Would you mind bumping the version to release a new one on pypy?

**Comment by MissiaL** [comment]
Yes, I can do that

**Comment by frallain** [comment]
@MissiaL Also I am sorry, I broke the README, let me fix that...

**Comment by MissiaL** [comment]
Not to worry. I now will correct with a new release

**Comment by MissiaL** [comment]
Version updated to 0.1.9

**Pull request merged**
